# Generated by Django 3.2.4 on 2021-06-20 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('adult', models.IntegerField(blank=True, default=1, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
